web:
  image: naflm/php5-master
  ports:
    - "8080:80"
# uncomment if you are going to deploy the code locally (develop php code)
#  volumes:
#    - ./src:/var/www/html/
  links:
    - db

db:
  image: mysql
#  volumes:
#    - /var/lib/mysql
  environment:
    - MYSQL_DATABASE=obblmdb
    - MYSQL_USER=obblm
    - MYSQL_PASSWORD=obbpaSSw0rd
    - MYSQL_ROOT_PASSWORD=my-secret-pw